---
# tasks file for prod
- name: Install Tomcat
  apt: name={{item}} state=present
  with_items:
    - tomcat9
    
- name: Ensure Tomcat is present
  service:
   name: tomcat9
   state: started
   
- name: Copy war file
  synchronize:
     src: "{{ dest_war_file }}"
     dest: "{{ dest_tomcat_webapp }}"
  delegate_to: 84.201.178.88